<?xml version="1.0" ?>
<testsuite name="ToDo-20230604145237" tests="1" time="15.605" failures="0" errors="1">
	<testcase classname="ToDo" name="test_counter" time="15.605">
		<error type="AssertionError" message="&lt;selenium.webdriver.remote.webelement.Web[102 chars]_4&quot;)&gt; != 1"><![CDATA[Traceback (most recent call last):
  File "/home/magdalena/webapp-test/test_script.py", line 122, in test_counter
    self.assertEqual(counter, 1)
AssertionError: <selenium.webdriver.remote.webelement.Web[102 chars]_4")> != 1
]]></error>
	</testcase>
	<system-out><![CDATA[<selenium.webdriver.remote.webelement.WebElement (session="1de54571bb614f46b6d903a6a060813d", element="3660EC5C798B38CA2E8C6E6ADA611D0D_element_4")>
<class 'selenium.webdriver.remote.webelement.WebElement'>
]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
